// <auto-generated />
namespace Default_Template_MVC.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class testetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201743198_teste-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
